### ISSUE TITLE
Can't get anything to load.

### ISSUE THREAD

**Issue by hollowaytyl** [surayashivji/PotterPics#1]
Checking out your project and nothing happens or load. The refresh control just spins continuously. Any suggestions on a fix?

**Comment by surayashivji** [comment]
Did you login with the Facebook account? Are you getting any errors? Also, if the refresh control is spinning continuously that usually has to do with internet access to connect to the database.

**Comment by hollowaytyl** [comment]
Everything is working fine. I discovered my problem which is something you should look for. I had two emails connected to my Facebook account. The email that I used as my primary contact was an email I created years ago. Apparently when I first created my Facebook account, Facebook wasn't doing email confirmations then. So because my old email address was being used as a primary contact and it wasn't confirmed, it kept loading infinitely and crashing the app. I changed primary contact to an email I verified & created a few test accounts on Facebook and everything is working fine. So just a heads up: users without Facebook confirmed emails won't be able to use the app.

**Comment by surayashivji** [comment]
Oh interesting, I will look into this. However, you can't actually login to the app with your personal Facebook account because it's not a live app and I have to manually add testers. Did you end up getting it working with the test account provided in the README?
