### ISSUE TITLE
fire abase not working 

### ISSUE THREAD

**Issue by davut5** [surayashivji/PotterPics#2]
when i tried it not downg any thing.  :(  
could you please  share json  file?

**Comment by surayashivji** [comment]
Are you logged in with the test Facebook account? What error are you receiving? If the loading progress is loading continuously it is most likely your internet. There is no static json file I'm using Firebase's real time database.

**Comment by surayashivji** [comment]
Any updates @davut5?

**Comment by davut5** [comment]
@surayashivji i write a post but not show in timeline.. :(

**Comment by surayashivji** [comment]
Are you using PotterPics?

**Comment by davut5** [comment]
yes..

**Comment by surayashivji** [comment]
May I see your source code? If you're using PotterPics in your own app you should set up your own Firebase database separate from the one I'm using.
