### ISSUE TITLE
Posting to firebase using front camera flips image upside down. 

### ISSUE THREAD

**Issue by leandrosh** [surayashivji/PotterPics#3]
Using a custom camera that allows access to the system camera causes the image to post upside down when using the front camera. Any idea why? Only images taken with the back camera look correct.

**Comment by surayashivji** [comment]
This has to do with the camera not rotating the UImage before saving it. I faced this issue (with the back camera) and fixed it by rotating them myself. If you want to have a UIImage as a PNG, it'll be rotated in the wrong way. Check http://stackoverflow.com/questions/3554244/uiimagepngrepresentation-issues-images-rotated-by-90-degrees and let me know if you have any other questions!
