### ISSUE TITLE
Multiple authentication services

### ISSUE THREAD

**Issue by tylerthinkofus** [surayashivji/PotterPics#4]
Cool concept. I'm working on a similar project from Skillshare and I'm also using Facebook authentication to grab profile name and picture. I'm curious about how you would go about loading the profile view controller when that information isn't provided (when the user chooses to sign up using a different method other than Facebook). Without it, the viewcontroller crashes.

**Comment by surayashivji** [comment]
If the user didn't authenticate via Facebook, I would load a default placeholder image and then allow the user to upload his/her own image through the viewcontroller.

**Comment by tylerthinkofus** [comment]
Makes sense. I checked out your code and tried making a sign in page. I'm
getting an error in the extract values section. Loading the default image
is clever, but what about the name, profile pic, email and etc? How would
you deal with that not being there?


Sorry to intrude on your code. Just wanted to see why mine isn't working
correctly. Seems like the same problem is occurring.

**Comment by surayashivji** [comment]
No intrusion! The name and email (and arguably profile picture) should be extracted from your sign up form. So you could have a sign up form that asks users for their name, email, and a picture, and then load their profile with that data.

**Comment by tylerthinkofus** [comment]
Hello my friend, thank you for last nights suggestion. I found this tutorial last night and adapted it to my code. Works perfectly - I know have email and Facebook log in intergrated. 😁

**Comment by surayashivji** [comment]
That's great!
